### DISCUSSION TITLE
Can I use cdk8s fromd deno?

### DISCUSSION THREAD

**Discussion by unicomp21** [cdk8s-team/cdk8s#1979] [Q&A] [answered]

**Comment by tesharp** [comment, marked as answer]
Yes, it is possible with `deno` 1.28. Just import it as npm packages. Something like this, not entirely working since a bit copy / paste..

**main.ts:**
```typescript
import * as cdk8s from 'npm:cdk8s';
import { Construct } from 'npm:constructs';

export class MyChart extends cdk8s.Chart {
  constructor(scope: Construct, id: string, props: cdk8s.ChartProps) {
    super(scope, id, props);

    ...
  }
}
```

**cdk8s.yaml:**
```yaml
language: typescript
app: deno run --allow-env --allow-write --allow-read main.ts
imports:
  - k8s
```
