### ISSUE TITLE
Can I use CDK8S_DISABLE_SORT in metadata?

### ISSUE THREAD

**Issue by gillerst1** [cdk8s-team/cdk8s#1081]
### Description of the feature or enhancement:
Related in #525 issue
I want use this option in metadata

### Use Case:
```
spec:
      containers:
        - command:
            - run
          envFrom:
            - configMapRef:
                name: db-env
          image: mongo
          imagePullPolicy: IfNotPresent
```

### Proposed Solution:
in the order within the ts file
```
{
        name: {NAME}
        image: {IMAGE}
        imagePullPolicy: "IfNotPresent",
        command: [
          "sh",
          "-c",
        ],
        volumeMounts: [
          {
            name: {NAME}
            mountPath: "/opt/data"
          },
        ],
      },
}

spec:
      containers:
          image: mongo
          imagePullPolicy: IfNotPresent
        - command:
            - run
          envFrom:
            - configMapRef:
                name: db-env
```

### Other:

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
