### ISSUE TITLE
Unable to set multiple resources for the Role

### ISSUE THREAD

**Issue by bittracer** [cdk8s-team/cdk8s#1098]
### Change `resourceType` type from String to support List

I am generating the manifest using CDK8s for the RBAC using following:

```
const roleProps: kplus.RoleProps = {
      metadata: {
        labels:
          {
            'app.kubernetes.io/component': 'controller',
            'app.kubernetes.io/instance': 'ingress-nginx',
            'app.kubernetes.io/name': 'ingress-nginx',
            'app.kubernetes.io/part-of': 'ingress-nginx',
            'app.kubernetes.io/version': '1.5.1',
          },
        name: 'ingress-nginx-admission',
        namespace: nameSpace.name,
      },
    };
    const role = new kplus.Role(this, 'ingress-nginx', roleProps);
    roleyallowRead(ApiResource.custom({
      apiGroup: '',
      resourceType: ['configmaps', 'pods', 'secrets'], -> Unable to specify like this
    }));
```

But I am unable to add multiple `resourceType` in above.

### Expected output:

I am expecting following output but since the resourceType is of type type `String` and not `List` I am unable to provide multiple resources.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.3.0
  name: ingress-nginx
  namespace: ingress-nginx-external
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
```

---

This is a :rocket: Feature Request
