### ISSUE TITLE
Support resourceNames field for Role in cdk8s-plus-* 

### ISSUE THREAD

**Issue by bittracer** [cdk8s-team/cdk8s#1099]
Need a way to add the **resourceNames** in the RBAC Role. Today this is something not supported. 

I am trying the following way:

```
const role = new kplus.Role(this, 'ingress-nginx', roleProps);
role.allow(['get', 'update'], ApiResource.custom({
      apiGroup: 'networking.k8s.io',
      resourceType: 'configmaps',      
}));
```
If we can do something like below, that would be great:

```
const role = new kplus.Role(this, 'ingress-nginx', roleProps);
role.allow(['get', 'update'], ApiResource.custom({
      apiGroup: 'networking.k8s.io',
      resourceType: 'configmaps',
      resourceNames: 'ingress-controller-leader'    <-- New feature
}));
```

As suggested by @iliapolo, there's a hacky way to do the same.

```
const role = new kplus.Role(this, 'Role');

const leader = {
  apiGroup: '',
  resourceType: 'configmaps',
  resourceNames: 'ingress-controller-leader'
};

role.allowGet(leader);
role.allowUpdate(leader);
role.allowCreate(kplus.ApiResource.CONFIG_MAPS); 
```

**Generated output:**

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cdk8s-ts-role-c8e41cad
rules:
  - apiGroups:
      - ""
    resourceNames:
      - ingress-controller-leader
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - ""
    resourceNames:
      - ingress-controller-leader
    resources:
      - configmaps
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
```

Additional reference:  https://kubernetes.github.io/ingress-nginx/deploy/rbac/
