### ISSUE TITLE
CRD Manifests Are Not Ordered

### ISSUE THREAD

**Issue by akefirad** [cdk8s-team/cdk8s#1103]
### Description of the bug:
I'm not sure if this is a bug or feature, but for some reason `VirtualService` (a CRD of Istio, imported using `import` command) manifest doesn't get sorted:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
spec:
  gateways:
    - istio-system/api-gateway
  hosts:
    - my-host
  http:
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: my-service
            port:
              number: 8080
metadata:
  labels:
    app: my-service
    cdk8s.io/metadata.addr: my-service-deployment-c89b7b33
  name: my-service
  namespace: my-namespace
```

### Reproduction Steps:
Either import istio CRDs or use imported [networking.istio.io.ts.txt](https://github.com/cdk8s-team/cdk8s/files/10248640/networking.istio.io.ts.txt) (change the extension) and create a resource and then run `synth`. I expect the metadata to be before spec. Right?

### Environment:
  - **Framework Version**:  `2.3.0`
  - **OS**: maOS 12.6

---

This is :bug: Bug Report
