### ISSUE TITLE
Resource Unit Should Not Be Converted

### ISSUE THREAD

**Issue by akefirad** [cdk8s-team/cdk8s#1166]
### Description of the bug:
Using `Size.gibibytes(2)` generates `2048Mi` instead of `2Gi`. This is a bit of a problem in GitOps setup (since it shows there's a diff). Essentially I guess ideally there should be no conversions of such kind at all, if possible.

### Reproduction Steps:
My code is like this:
```typescript
    const deployment = new Deployment(this, "deployment", {
      replicas: props.replicas,
    });

    deployment.addContainer({
      image: props.image,
      portNumber: props.port,
      resources: {
        memory: {
          request: Size.gibibytes(1),
          limit: Size.gibibytes(2),
        },
      },
    });
```
(Let me know if the above code doesn't work for you. Happy to provide a sample project.)

### Error Log:
And the output contains:
```yaml
apiVersion: apps/v1
kind: Deployment
#... other stuff
          resources:
            limits:
              memory: 2048Mi
            requests:
              memory: 1024Mi
# ... other stuff
```

### Environment:

  - **Framework Version**: CDK8S v2.5.78
  - **OS**: macOS v13.1

### Other:

---

This is :bug: Bug Report
