### ISSUE TITLE
Importing from same remote source only applies the latest import.

### ISSUE THREAD

**Issue by joonvena** [cdk8s-team/cdk8s#1250]
### Description of the bug:

When i'm importing multiple CRD's from same remote repository only the latest gets imported.

### Reproduction Steps:

```yaml
language: python
app: python main.py
imports:
  - k8s
  - https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crds/bases/external-secrets.io_externalsecrets.yaml
  - https://raw.githubusercontent.com/external-secrets/external-secrets/main/config/crds/bases/external-secrets.io_secretstores.yaml
```

Run `cdk8s import`

```python
...
from imports.io import external_secrets

# Works
external_secrets.SecretStore(
...

# Doesn't work
external_secrets.ExternalSecret(
...
```

If i change the import order then the `ExternalSecret` is available but `SecretStore` is not. 

### Error Log:

There is no visible error messages.

### Environment:

  - **Framework Version**: 2.1.161
  - **OS**: macOS Monterey

### Other:

---

This is :bug: Bug Report
