### ISSUE TITLE
Java property getters Import Conflict for Prometheus CRD's

### ISSUE THREAD

**Issue by yuriy-yarosh** [cdk8s-team/cdk8s#1323]
Can't import Prometheus Operator [Prometheus CRD](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-operator-crds/templates/crd-prometheuses.yaml#L6690), due to naming conflict

```
  | error JSII5000: Methods and properties cannot have names like "getXxx": those conflict with Java property getters. Rename "PrometheusSpecThanos.getConfigInterval"
  | error JSII5000: Methods and properties cannot have names like "getXxx": those conflict with Java property getters. Rename "PrometheusSpecThanos.getConfigTimeout"
```

```yaml
getConfigInterval:
  description: How often to retrieve the Prometheus configuration.
  pattern: ^(0|(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?)$
  type: string
getConfigTimeout:
  description: Maximum time to wait when retrieving the Prometheus
    configuration.
  pattern: ^(0|(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?)$
  type: string
```

I've renamed 'em to 

```yaml
PrometheusSpecThanos.getConfigInterval:
  description: How often to retrieve the Prometheus configuration.
  pattern: ^(0|(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?)$
  type: string
PrometheusSpecThanos.getConfigTimeout:
  description: Maximum time to wait when retrieving the Prometheus
    configuration.
  pattern: ^(0|(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?)$
  type: string
```

But it generated

```go
// How often to retrieve the Prometheus configuration.
PrometheusSpecThanosGetConfigInterval *string `field:"optional" json:"prometheusSpecThanosGetConfigInterval" yaml:"prometheusSpecThanosGetConfigInterval"`
// Maximum time to wait when retrieving the Prometheus configuration.
PrometheusSpecThanosGetConfigTimeout *string `field:"optional" json:"prometheusSpecThanosGetConfigTimeout" yaml:"prometheusSpecThanosGetConfigTimeout"`
```

for golang... So, I had to fix it manually, afterwards to make it work by renaming the `json` and `yaml` tags manually.

### Environment:

```json
"devDependencies": {
  "cdk8s-cli": "^2.2.32",
  "cdk8s": "^2.7.59",
  "constructs": "^10.2.20",
  "jsii": "^5.0.7"
}
```
This is :bug: Bug Report
