### ISSUE TITLE
cdk8s doesn't import YAML anchors

### ISSUE THREAD

**Issue by yuriy-yarosh** [cdk8s-team/cdk8s#1329]
### Description of the bug:

Trying to import knative-eventing CRDS as is, and it turned out that CDK8S unable to merge yaml anchors.

An example of faulty CRDS yaml

```yaml
items:
type: object
x-kubernetes-preserve-unknown-fields: true
properties:
  delivery:
    type: object
    properties:
      deadLetterSink:
        type: object
        properties: &addressableProperties
          ref:
            type: object
            properties:
              apiVersion:
                type: string
              kind:
                type: string
              name:
                type: string
              namespace:
                type: string
          uri:
            type: string
      retry:
        type: integer
        format: int32
  filter:
    type: object
    properties:
      !!merge <<: *addressableProperties
  reply:
    type: object
    properties:
      !!merge <<: *addressableProperties
  subscriber:
    type: object
    properties:
      !!merge <<: *addressableProperties
```

### Reproduction Steps:

1. Download the existing [release](https://github.com/knative/eventing/releases/download/knative-v1.10.0/eventing-crds.yaml) Knative Eventing CRDS.
2. Try to import it with 

```yaml
language: go
imports:
  - knative_eventing:=./eventing-crds.yaml
```

```
cdk8s import
```

### Error Log:

```
Error: Key '<<' contains non standard characters (Must match regex '/^(\w|\.|\/|-|#|,)*$/')
    at SafeReviver._sanitizeObj (/home/yura/.asdf/installs/nodejs/18.16.0/lib/node_modules/cdk8s-cli/lib/reviver.js:40:23)
    at SafeReviver._sanitizeObj (/home/yura/.asdf/installs/nodejs/18.16.0/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/yura/.asdf/installs/nodejs/18.16.0/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/yura/.asdf/installs/nodejs/18.16.0/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/yura/.asdf/installs/nodejs/18.16.0/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/yura/.asdf/installs/nodejs/18.16.0/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/yura/.asdf/installs/nodejs/18.16.0/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/yura/.asdf/installs/nodejs/18.16.0/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/yura/.asdf/installs/nodejs/18.16.0/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/yura/.asdf/installs/nodejs/18.16.0/lib/node_modules/cdk8s-cli/lib/reviver.js:47:22
```

### Environment:

```json
  "dependencies": {
    "cdk8s": "^2.7.70",
    "cdk8s-cli": "^2.2.37",
    "constructs": "^10.2.28",
    "jsii": "^5.0.8",
    "jsii-rosetta": "^5.0.8"
  },
```

---

This is :bug: Bug Report
