### ISSUE TITLE
cdk8s import behavior changed?

### ISSUE THREAD

**Issue by shinebayar-g** [cdk8s-team/cdk8s#1442]
### Description of the bug:

Looks like `cdk8s import` command is recently changed.

### Reproduction Steps:

`cdk8s.yaml` content:

```yml
language: typescript
imports:
  - 1.24:=k8s@1.24.0
  - 1.25:=k8s@1.25.0
  - 1.26:=k8s@1.26.0
  - ....
```

When I run `npx cdk8s import --output packages/my-lib/imports`, `cdk8s.yaml` is updated to

```yml
output: dist # ??
pluginsDirectory: /Users/MYUSERNAME/.cdk8s/plugins # ??
language: typescript
imports:
  - 1.24:=k8s@1.24.0
  - 1.25:=k8s@1.25.0
  - 1.26:=k8s@1.26.0
  - k8s@1.24.0 # ??
  - k8s@1.25.0 # ??
  - k8s@1.26.0 # ??
  - ....
```

### Environment:

  - **Framework Version**:
  - **OS**:
```
❯ npx cdk8s --version
2.50.0
```

### Other:

---

This is :bug: Bug Report
