### ISSUE TITLE
[DRAFT] Namespace being generated for non-namespaced resources

### ISSUE THREAD

**Issue by vinayak-kukreja** [cdk8s-team/cdk8s#1618]
# [DRAFT] Creating a placeholder issue to add instances of this bug

### Environment:

  - **Framework Version**:
  - **OS**:

### Other:
Related Issue: https://github.com/cdk8s-team/cdk8s-plus/issues/4239

---

This is :bug: Bug Report

**Comment by drmorr0** [comment]
I just ran into this, came here to see if anybody had reported it yet.  If you assign a namespace to a `Chart` object, and then create cluster-scoped resources inside that chart, those resources get assigned a namespace.

Example:

```python
app = App()
chart = Chart(app, "some-chart", namespace="foo")
ns = k8s.KubeNamespace(chart, "namespace")
app.synth()
```

produces

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: some-chart-namespace-c8d9d43d
  namespace: foo
```

This is the identical issue to #1558 which I believe was incorrectly marked as closed (although there is a nice workaround for it)
