### ISSUE TITLE
Error rendering container command from synthHelm

### ISSUE THREAD

**Issue by leawn** [cdk8s-team/cdk8s#1679]
### Description of the bug:

I'm facing an issue when trying to render this helm chart (https://github.com/dagster-io/dagster/tree/1.5.6/helm/dagster).
The issue is that the container command doesn't get rendered properly
Here is the rendered deployment after `synthHelm`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: dauano
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dagster
    app.kubernetes.io/version: 1.5.6
    component: dagster-webserver
    helm.sh/chart: dagster-1.5.6
  name: dauano-dagster-webserver
  namespace: dauano
"dagster-webserver -h 0.0.0.0 -p 80 -w /dagster-workspace/workspace.yaml\" ] env":
  - name: DAGSTER_PG_PASSWORD
    valueFrom:
      secretKeyRef:
        key: postgresql-password
        name: dagster-postgresql-secret
envFrom:
  - configMapRef:
      name: dauano-dagster-webserver-env
ports:
  - containerPort: 80
    name: http
    protocol: TCP
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /server_info
    port: 80
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 10
resources: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dauano
      app.kubernetes.io/name: dagster
      component: dagster-webserver
  template:
    metadata:
      annotations:
        checksum/dagster-instance: c1e8d4a3b9806726353e62dabe00e25ee62e236f476d4e530a34d6a805c5c176
        checksum/dagster-workspace: a27026d0146508526a6f9c20cb27c5da05655d8fb7efd5227a2ab8609cc8d099
      labels:
        app.kubernetes.io/instance: dauano
        app.kubernetes.io/name: dagster
        component: dagster-webserver
    spec:
      containers:
        - command:
            - /bin/bash
            - -c
            - ""
          image: docker.io/dagster/dagster-celery-k8s:1.5.6
          imagePullPolicy: Always
          name: dagster
          securityContext: {}
      initContainers:
        - command:
            - sh
            - -c
            - until pg_isready -h dauano-postgresql -p 5432 -U test; do echo waiting for database; sleep 2; done;
          image: library/postgres:14.6
          imagePullPolicy: IfNotPresent
          name: check-db-ready
          securityContext: {}
        - command:
            - sh
            - -c
            - until nslookup k8s-example-user-code-1; do echo waiting for user service; sleep 2; done
          image: docker.io/busybox:1.28
          name: init-user-deployment-k8s-example-user-code-1
          securityContext: {}
      securityContext: {}
      serviceAccountName: dauano-dagster
volumeMounts:
  - mountPath: /opt/dagster/dagster_home/dagster.yaml
    name: dagster-instance
    subPath: dagster.yaml
  - mountPath: /dagster-workspace/
    name: dagster-workspace-yaml
volumes:
  - configMap:
      name: dauano-dagster-instance
    name: dagster-instance
  - configMap:
      name: dauano-dagster-workspace-yaml
    name: dagster-workspace-yaml
``` 

So, after the block of metadata, namespace name you see a line `"dagster-webserver -h 0.0.0.0 -p 80 -w /dagster-workspace/workspace.yaml\" ] env":`. This line is actually a command that is defined here https://github.com/dagster-io/dagster/blob/1.5.6/helm/dagster/templates/helpers/_helpers.tpl as a `dagster.webserver.dagsterWebserverCommand`.
First, I thought that was a problem with configuration & tried to change it multiple times.

Then I cloned the v1.5.6 of this helm chart locally, updated with the following values:

```
ingress:
  apiVersion: 'networking.k8s.io/v1/Ingress'
  enabled: true
  ingressClassName: nginx
  dagsterWebserver:
    host: '$hostname'
``` 

And ran `helm template . --values values-valid.yaml --debug > debug.yaml` command to generate the rendered YAML.
Here is the same deployment:

```
# Source: dagster/templates/deployment-webserver.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-dagster-webserver
  labels:
    helm.sh/chart: dagster-0.0.1-dev
    app.kubernetes.io/name: dagster
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "dev"
    app.kubernetes.io/managed-by: Helm
    component: dagster-webserver
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dagster
      app.kubernetes.io/instance: RELEASE-NAME
      component: dagster-webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dagster
        app.kubernetes.io/instance: RELEASE-NAME
        component: dagster-webserver
      annotations:
        checksum/dagster-workspace: e4c42a057b8e3665a44162c774cbd3ec55c0641d9733b590a67c6dc619b2da56
        checksum/dagster-instance: 102767b51be3525d991d8434aeb851d3386daaa5940e626397fb0e3073fd45a1
    spec:
      serviceAccountName: RELEASE-NAME-dagster
      securityContext:
        {}
      initContainers:
        - name: check-db-ready
          image: "library/postgres:14.6"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until pg_isready -h RELEASE-NAME-postgresql -p 5432 -U test; do echo waiting for database; sleep 2; done;']
          securityContext:
            {}
        - name: "init-user-deployment-k8s-example-user-code-1"
          image: "docker.io/busybox:1.28"
          command: ['sh', '-c', "until nslookup k8s-example-user-code-1; do echo waiting for user service; sleep 2; done"]
          securityContext:
            {}
      containers:
        - name: dagster
          securityContext:
            {}
          imagePullPolicy: Always
          image: "docker.io/dagster/dagster-celery-k8s:0.0.1-dev"
          command: [
            "/bin/bash",
            "-c",
            "
dagster-webserver -h 0.0.0.0 -p 80 -w /dagster-workspace/workspace.yaml"
          ]
          env:
            - name: DAGSTER_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "dagster-postgresql-secret"
                  key: postgresql-password
            # This is a list by default, but for backcompat it can be a map. As
            # a map it's written to the webserver-env configmap.
          envFrom:
            - configMapRef:
                name: RELEASE-NAME-dagster-webserver-env
          volumeMounts:
            - name: dagster-instance
              mountPath: "/opt/dagster/dagster_home/dagster.yaml"
              subPath: dagster.yaml
            # Do not use `subPath` to allow the configmap to update if modified
            - name: dagster-workspace-yaml
              mountPath: "/dagster-workspace/"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /server_info
              port: 80
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 10

      volumes:
        - name: dagster-instance
          configMap:
            name: RELEASE-NAME-dagster-instance
        - name: dagster-workspace-yaml
          configMap:
            name: RELEASE-NAME-dagster-workspace-yaml
``` 

So, as you can see, using the Helm CLI I don't get the same outcome as if I use cdk8s `synthHelm`. The command gets rendered correctly and in place.

### Reproduction Steps:

I'm creating the following HelmChart class that extends Chart:

```
export class HelmChart extends Chart {
  constructor({
    scope,
    name,
    namespace,
    chart,
    version,
    values,
  }: {
    scope: Construct;
    name: string;
    namespace: string;
    chart: string;
    version: string;
    values: HelmProps['values'];
  }) {
    // set  namespace at the chart level
    super(scope, name, { namespace });

    new Helm(this, name, {
      chart,
      values,
      releaseName: namespace,
      helmFlags: ['--version', version, '--namespace', namespace, '--include-crds'],
    });
  }
}
``` 

and then in a function, I create a new HelmChart instance:
```
new HelmChart({ scope, name, namespace, chart, version, values });
``` 
With the following values:
```
scope: <root>,
name: dauano,
namespace: dauano,
chart: helm/dagster,
version: 1.5.6,
values: {"ingress":{"enabled":true,"apiVersion":"networking.k8s.io/v1/Ingress","dagsterWebserver":{"host":"$hostname"},"ingressClassName":"nginx"}}
``` 

### Error Log:
There is no actual error log, while then when applying the k8s resources it throws no error, so it was very hard to trace this error back to `synthHelm`. In the first place, I noticed that the `webserver` pod ended up in a CrashLoopBackoff. Then noticed that it was running this command:
```
command:
            - /bin/bash
            - -c
            - ""
``` 
which resulted in repeated exit

### Environment:

"cdk8s": "^2.6.21"
"cdk8s-plus-25": "2.3.26"
"constructs": "10.1.222"
"typescript": "4.7.4"
"node": ">=18.12"
Deployment environment:
k8s: v1.27.7-gke.1121000

### Other:
What's interesting is that there is another deployment that uses container with a command the same way as the `webserver` one. It's the `daemon` deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: dauano
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dagster
    app.kubernetes.io/version: 1.5.6
    component: dagster-daemon
    deployment: daemon
    helm.sh/chart: dagster-1.5.6
  name: dauano-dagster-daemon
  namespace: dauano
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dauano
      app.kubernetes.io/name: dagster
      component: dagster-daemon
      deployment: daemon
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/dagster-instance: c1e8d4a3b9806726353e62dabe00e25ee62e236f476d4e530a34d6a805c5c176
        checksum/dagster-workspace: a27026d0146508526a6f9c20cb27c5da05655d8fb7efd5227a2ab8609cc8d099
      labels:
        app.kubernetes.io/instance: dauano
        app.kubernetes.io/name: dagster
        component: dagster-daemon
        deployment: daemon
    spec:
      affinity: {}
      containers:
        - command:
            - /bin/bash
            - -c
            - dagster-daemon run -w /dagster-workspace/workspace.yaml
          env:
            - name: DAGSTER_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: dagster-postgresql-secret
            - name: DAGSTER_DAEMON_HEARTBEAT_TOLERANCE
              value: "1800"
          envFrom:
            - configMapRef:
                name: dauano-dagster-daemon-env
          image: docker.io/dagster/dagster-celery-k8s:1.5.6
          imagePullPolicy: Always
          name: dagster
          resources: {}
          securityContext: {}
          volumeMounts:
            - mountPath: /opt/dagster/dagster_home/dagster.yaml
              name: dagster-instance
              subPath: dagster.yaml
            - mountPath: /dagster-workspace/
              name: dagster-workspace-yaml
      imagePullSecrets: []
      initContainers:
        - command:
            - sh
            - -c
            - until pg_isready -h dauano-postgresql -p 5432 -U test; do echo waiting for database; sleep 2; done;
          image: library/postgres:14.6
          imagePullPolicy: IfNotPresent
          name: check-db-ready
          securityContext: {}
        - command:
            - sh
            - -c
            - until nslookup k8s-example-user-code-1; do echo waiting for user service; sleep 2; done
          image: docker.io/busybox:1.28
          name: init-user-deployment-k8s-example-user-code-1
          securityContext: {}
      nodeSelector: {}
      securityContext: {}
      serviceAccountName: dauano-dagster
      tolerations: []
      volumes:
        - configMap:
            name: dauano-dagster-instance
          name: dagster-instance
        - configMap:
            name: dauano-dagster-workspace-yaml
          name: dagster-workspace-yaml
``` 

And here the command has a similar content but somehow get rendered correctly
The command for `daemon` is defined here: https://github.com/dagster-io/dagster/blob/1.5.6/helm/dagster/templates/helpers/_helpers.tpl

---

This is :bug: Bug Report
