### ISSUE TITLE
CRD import with x-kubernetes-preserve-unknown-fields: true does not work

### ISSUE THREAD

**Issue by yairyairyair** [cdk8s-team/cdk8s#2152]
take an example crd with x-kubernetes-preserve-unknown-fields: true

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.core.example.com
spec:
  group: core.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: examples
    singular: example
    kind: Example
    shortNames:
      - ex
```

generate its types via cdk8s import example-crd.yaml

You will have this code at the end which allow only metadata without a spec of typecript type any

```
/**
 * Converts an object of type 'ExampleProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_ExampleProps(obj: ExampleProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */


```

Bottom line: need to add support for x-kubernetes-preserve-unknown-fields
