### ISSUE TITLE
`cdk8s synth -p` fails to insert necessary document start markers

### ISSUE THREAD

**Issue by rassie** [cdk8s-team/cdk8s#2155]
### Description of the bug:
If `cdk8s synth -p`  is used with any other `yamlOutputType` setting on the app than `YamlOutputType.FILE_PER_APP`, the YAML being output is missing some document start markers.

### Reproduction Steps:

1. Create a new `cdk8s` project
2. Adapt this project as per https://cdk8s.io/docs/latest/getting-started/#importing-constructs-for-the-kubernetes-api
3. Change `const app = new App();` to `const app = new App({ yamlOutputType: YamlOutputType.FILE_PER_RESOURCE });` in `main.ts`
4. Execute `npm run compile && cdk8s synth -p`
5. Observe the following output:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment-c8c7fda7
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-k8s
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - image: paulbouwer/hello-kubernetes:1.7
          name: hello-kubernetes
          ports:
            - containerPort: 8080
apiVersion: v1
kind: Service
metadata:
  name: hello-service-c8c17160
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-k8s
  type: LoadBalancer
```

As you can see, this output is missing the YAML document start marker `---` before the second resource. 

### Other:

The reason is obviously that `synth -p` is not outputting documents one by one, but instead it runs `synth` into a temporary directory and then concatenated the files generated. The document start marker is missing at the exact spot where two files come together. For obvious reasons, this is not a problem with `YamlOutputType.FILE_PER_APP`. 

A simple solution could be adding a document start marker to each file or each resource by default (which is recommended anyway, e.g. in [yamllint](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_start)). 

---

This is :bug: Bug Report
