### ISSUE TITLE
How to set fields to `null` literral in go

### ISSUE THREAD

**Issue by tgermain** [cdk8s-team/cdk8s#2162]
### Description of the bug:

I'm using cdk8s with go and I'm having trouble setting some fields to `null` literal.

#### Why do I need to set fields to `null` in the first place? 

When creating/updating resource using `kubectl apply`, it does a 3 way merge between the existing k8s resource on the cluster and what you want to apply.

For instance, if you already have a k8s resource with a `foo: bar` label like:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    foo: bar
    baz: baz
  name: my-cm
```

and you want to remove the `foo` label, applying a resource like:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  # no more foo label
    baz: baz
  name: my-cm
```
is not enough because of the 3 way merge. It will work if you try to apply the same manifest to a brand new k8s cluster but not on one where the `my-cm` configmap already have the `foo` label.

A common trick I've used in the past and that was implemented in https://github.com/kubernetes/kubernetes/pull/40630 is to set the field you want to remove to `null` literal:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    foo: null
    baz: baz
  name: my-cm
```

This yaml manifest will remove the `foo` label if it's already present in the existing resource.

### Reproduction Steps:

This is my test cdk8s app:
```go
package main

import (
	"fmt"

	"example.com/cdk8s-demo/imports/k8s"
	"github.com/aws/jsii-runtime-go"
	"github.com/cdk8s-team/cdk8s-core-go/cdk8s/v2"
)

func main() {
	app := cdk8s.NewApp(&cdk8s.AppProps{})

	chart := cdk8s.NewChart(app, jsii.String("my-chart"), &cdk8s.ChartProps{})

	labels := map[string]*string{
		"foo": jsii.String("bar"),
		"set-to-null": jsii.String("to-be-replaced"),
	}
	k8s.NewKubeConfigMap(chart, jsii.String("my-cm"), &k8s.KubeConfigMapProps{
		Metadata: &k8s.ObjectMeta{
			Labels: &labels,
		}})
	fmt.Println(*app.SynthYaml())
}
```
It a go module named `example.com/cdk8s-demo/imports/k8s`.
Under `example.com/cdk8s-demo/imports/k8s` I've imported k8s api objects using `cdk8s import k8s -l go`.

When run using `go run main.go` it produce:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    foo: bar
    set-to-null: to-be-replaced
  name: my-chart-my-cm-c841940f
```

### Environment:

  - **Framework Version**: `github.com/cdk8s-team/cdk8s-core-go/cdk8s/v2 v2.68.71`
  - **OS**: linux

### Other:

What I have already tried:

Using `"set-to-null": jsii.String(""),` -> it renders an empty string in the yaml (expected).

Using `"set-to-null": jsii.String("null"),` -> it renders a `"null"` string in the yaml (expected).

Using [json-patch](https://cdk8s.io/docs/latest/basics/escape-hatches/#patching-api-objects-directly):
```go
package main

import (
	"fmt"

	"example.com/cdk8s-demo/imports/k8s"
	"github.com/aws/jsii-runtime-go"
	"github.com/cdk8s-team/cdk8s-core-go/cdk8s/v2"
)

func main() {
	app := cdk8s.NewApp(&cdk8s.AppProps{})

	chart := cdk8s.NewChart(app, jsii.String("my-chart"), &cdk8s.ChartProps{})

	labels := map[string]*string{
		"foo": jsii.String("bar"),
		"set-to-null": jsii.String(""),
	}
	cm:=k8s.NewKubeConfigMap(chart, jsii.String("my-cm"), &k8s.KubeConfigMapProps{
		Metadata: &k8s.ObjectMeta{
			Labels: &labels,
		}})

	cm.AddJsonPatch(cdk8s.JsonPatch_Replace(jsii.String("/metadata/labels/set-to-null"),"null"))
	fmt.Println(*app.SynthYaml())
}
```

`cm.AddJsonPatch(cdk8s.JsonPatch_Replace(jsii.String("/metadata/labels/set-to-null"),"null"))` -> render a `"null"` string in yaml
`cm.AddJsonPatch(cdk8s.JsonPatch_Replace(jsii.String("/metadata/labels/set-to-null"),""))` -> render a `""` string in yaml

Using pointer to empty interface:
```
	var i interface{}
	cm.AddJsonPatch(cdk8s.JsonPatch_Replace(jsii.String("/metadata/labels/set-to-null"), &i))
```
-> it removes the field completely.

I think a json path like `{"op": "replace","path": "/metadata/labels/set-to-null","value": null}` should work but I think the `null` literal in the json patch is lost at some point when go ---call---> jsii ---call---> typescript.

---

This is :bug: Bug Report
