### ISSUE TITLE
Escape hatches seem to not be working as expected

### ISSUE THREAD

**Issue by srfrnk** [cdk8s-team/cdk8s#2163]
### Description of the bug:

The following code:
```typescript
    var test = new KubeNamespace(this, "test", {
      metadata: {
        name: "test"
      }
    })

    test.addJsonPatch(JsonPatch.add("/spec", { 'test': 1 }))
```

Generates this:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
spec: {}
```

While AFAIK it should generate:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
spec:
  test: 1
```

### Reproduction Steps:

- insert code section into a new Cdk8s TS project
- run `npm run synth`

### Environment:
- Ubuntu 23
- Node  v18.20.0
- Cdk8s 2.198.65

---

This is :bug: Bug Report
