### ISSUE TITLE
workload Select() function updates the selector, but not the toPodSelectorConfig function

### ISSUE THREAD

**Issue by sthomson-wyn** [cdk8s-team/cdk8s#2238]
### Description of the bug:

When updating the matchlabels for a workload (say, a deployment), updating the pod selector does not update the output of the toPodSelectorConfig function

### Reproduction Steps:

Create a deployment, and update the selector labels:
```go
deployment := cdk8splus31.NewDeployment(chart, &deploymentName, &cdk8splus31.DeploymentProps{
		Select:                       boolPtr(false),
...
})
deployment.Select(cdk8splus31.LabelSelector_Of(&cdk8splus31.LabelSelectorOptions{
		Labels: &selectorLabels,
	}))
```
Results in the correct matchLabels in my deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      my-selectors: hello-world
```

However, when trying to use said deployment for a Service (or any other thing that uses an IPodSelector)
```go
svc := cdk8splus31.NewService(chart, strPtr(*config.ServiceName+"-svc"), &cdk8splus31.ServiceProps{
  Selector: deployment,
})
```
Results in
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    cdk8s.io/metadata.addr: my-deployment-c8aaf3f2
  type: ClusterIP
```

### Environment:

  - **Framework Version**: 2.198.254
  - **OS**: Ubuntu

### Other:

---

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@sthomson-wyn Just to make I understand, did you expect to see:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    my-selectors: hello-world
  type: ClusterIP
```

?
