### ISSUE TITLE
Support httpHeaders in Probes

### ISSUE THREAD

**Issue by burner1024** [cdk8s-team/cdk8s#2294]
### Description of the feature or enhancement:

Allow to set httpHeaders, like so https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes :
```yaml
startupProbe:
  httpGet:
    httpHeaders:
      - name: User-Agent
        value: MyUserAgent
```

### Use Case:
To allow probes to do basic authorization, for one.

### Other:

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
