### ISSUE TITLE
EnvFrom multiple refs should be separate

### ISSUE THREAD

**Issue by burner1024** [cdk8s-team/cdk8s#2295]
### Description of the bug:

`const deploymentEnv = new kplus.EnvFrom(depConfigMap, undefined, depSecret);`

Use it in `deployment.containers.envFrom`. Resulting yaml is

```yaml
- envFrom:
    - configMapRef:
      name: cmName
      secretRef:
      name: secretName
```

That won't work:
`Deployment.apps "dep" is invalid: spec.template.spec.containers[0].envFrom: Invalid value: "": may not have more than one field specified at a time`

Expected output:
```yaml
- envFrom:
    - configMapRef:
      name: cmName
    - secretRef:
      name: secretName
```

### Reproduction Steps:

See above

### Environment:

  - **Framework Version**: cdk8s-plus-30
  - **OS**:

### Other:

---

This is :bug: Bug Report
