### ISSUE TITLE
Publish constructs as custom resources

### ISSUE THREAD

**Issue by tabern** [cdk8s-team/cdk8s#24]
Implement a generic Kubernetes Operator which will allow publishing constructs as custom k8s resources.

## [hypothetical] README

You can use cdk8s to implement custom Kubernetes resources (CRDs) which are backed by a generic operator.

Let's take the [WebService](https://github.com/awslabs/cdk8s/blob/master/examples/typescript/web-service/web-service.ts) example and use cdk8s to publish it as a CRD.

<details><summary>CRD manifest</summary>

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: webservices.example.com
spec:
  group: example.com
  names:
    kind: WebService
    plural: webservices
    singular: webservice
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                containerPort:
                  type: integer
                image:
                  type: string
                port:
                  type: integer
                replicas:
                  type: integer
              required:
                - image
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
```

</details>

Here's how users will use this custom resource in a manifest (equivalent to [this example](https://github.com/awslabs/cdk8s/blob/master/examples/typescript/web-service/index.ts)):

```yaml
apiVersion: v1
group: com.example
kind: WebService
metadata:
  name: hello
spec:
  image: paulbouwer/hello-kubernetes:1.7
  replicas: 2
---
apiVersion: v1
group: com.example
kind: WebService
metadata:
  name: ghost
spec:
  image: ghost 
  containerPort: 2368
```

Here's a sketch for how you would expose the `WebService` construct through a CDK8s app:

```ts
import { WebService, WebServiceOptions } from './web-service';
import { App, Stdio } from 'cdk8s';

const app = new App({ outdir: Stdio.stdout }); // <-- sketch

const objects = Stdio.readYamlObjects();

// we might be able to offer some sugar for this
for (const obj of objects) {
  if (obj.kind !== 'WebService' || obj.group !== 'com.example') {
    throw new Error(`unsupported object kind ${obj.group}.${obj.kind}`);
  }

  new WebService(app, obj.metadata.name, obj.spec);
}

app.synth();
```

When this CDK8s app is executed:

```shell
node index.js
```

Here's what happens:

1. Read STDIN and parse it as Kubernetes manifest (multiple objects)
2. Define a new `WebService` instance for each object defined in the manifest
3. Pass `spec` of each object to the `WebServiceOptions` parameter of the `WebService` constructor.
4. Synthesize the result to STDOUT

### Operator Deployment

To serve this resource, we need to deploy an operator to our k8s cluster that will subscribe to changes for k8s objects of this kind, will invoke our CDK app with the updated manifest and apply the result to the cluster.

> NOTE: we will need #178 to be implemented so that the operator can apply with `--prune`. Otherwise, there is no way to delete resources.

Since cdk8s app can be written in any programming language and users need to be in control of the environment used during synthesis, we recommend to package your CDK app into a docker image which will be deployed as a _side car_ container with the operator image.

Therefore, to deploy a CDK-based custom resource to a cluster, we will need:

1. The CRD
2. A `Deployment` with two containers - the generic operator and the CDK app's sidecar image.
3. These containers will be connected through an http server.

### Sidecar Protocol

The sidecar container will start a CDK synthesizer server which exposes a local http endpoint used by the operator to trigger synthesis. The protocol will be a simple CGI-like? server where the request body is the updated YAML manifest and the response is the synthesized output. The server will spawn the CDK app (above) for every request, pass the request body to STDIN and send back STDOUT as the response body.

Alternatives considered:

- Operator spawns the CDK app within the same container: The main downside is that it will require that the runtime environment in that image will be suitable for both the CDK app (in any language) and the operator.
- Operator spawns the CDK app in a "docker in docker" setup. The main downside is that this will require privileged execution and will be more complicated from an image management perspective. Using a sidecar has the benefit of delegating all image management and spawning to k8s.
