### ISSUE TITLE
Add resourceNames qualifier to ClusterRolePolicyRule

### ISSUE THREAD

**Issue by Sahand1993** [cdk8s-team/cdk8s#2413]
### Description of the feature or enhancement:

Just like org.cdk8s.plus29.k8s.PolicyRule allows you to provide resourceNames as a qualifier for the privileges, so should org.cdk8s.plus29.ClusterRolePolicyRule. 

### Use Case:

Needed to achieve the equivalent of:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    role: myRole
  name: myRole
rules:
  - apiGroups:
      - ""
     resourceNames:
      - myConfigMap
     resources:
      - configmaps
     verbs:
      - get
      - list
      - watch

```

### Proposed Solution:

Not read up enough on the repo to do that.

### Other:

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by iliapolo** [comment]
@Sahand1993 the `resourceNames` property is abstracted (possibly not clearly enough) away in `cdk8s-plus`. You can achieve the result you need with:

```ts
const configMap = new kplus.ConfigMap(this, 'ConfigMap', {
  metadata: { name: 'myConfigMap' }
});
const clusterRole = new kplus.ClusterRole(this, 'ClusterRole');

// this will create the rule and apply the `resourceNames` qualifier
clusterRole.allowRead(configMap);
```

Notice how you don't need to specify neither `verbs` nor `resourceNames`, but the resulting manifest will do what you expect it do:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myConfigMap
immutable: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdk8s-playground-typescript-clusterrole-c804fb0f
rules:
  - apiGroups:
      - ""
    resourceNames:
      - myConfigMap
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
```

One caveat here is that unfortunately this doesn't work with imported config maps (i.e ones that aren't managed by the cdk8s core). 

Does this answer your needs?
