### ISSUE TITLE
Incorrect import of Helm charts w/ two consecutive capital letters

### ISSUE THREAD

**Issue by milesgranger** [cdk8s-team/cdk8s#2593]
### Description of the bug:

It appears importing some Helm charts which have parameters containing two consecutive capital letters fail to render correctly.

### Reproduction Steps:

```bash
cdk8s init typescript-app
```

---

```yaml
# cdk8s.yaml
language: typescript
app: ts-node main.ts
imports:
  - k8s@1.31.0
  - mlflowHelm:=helm:oci://registry-1.docker.io/bitnamicharts/mlflow@5.0.3
```

---

```bash
npm run import

cat imports/mlflowHelm-mlflow.ts | grep runUpgrade
   * @schema MlflowTracking#runUpgradeDB
  readonly runUpgradeDb?: boolean;
```

Note, I don't know if _this_ is why the problem exist, but in that helm chart, it's specified `runUpgradeDB` as noted in the docs following the `grep`, but typescript is camel.

When using and rendering the chart:

```typescript
// main.ts
import { Construct } from "constructs";
import { App, Chart, ChartProps } from "cdk8s";
import { Mlflow } from "./imports/mlflowHelm-mlflow";

export class MyChart extends Chart {
  constructor(scope: Construct, id: string, props: ChartProps = {}) {
    super(scope, id, props);

    // define resources here
    new Mlflow(this, "mlflow", {
      releaseName: "mlflow",
      values: {
        tracking: {
          runUpgradeDb: true,
        },
      },
    });
  }
}

const app = new App();
new MyChart(app, "tmp");
app.synth();
```

---

```bash
npm run compile
npm run synth

cat dist/tmp.k8s.yaml | grep upgrade -A 5 -B 5
```

---

```
❯ cat dist/tmp.k8s.yaml | grep upgrade -A 5 -B 5
              name: rendered-basic-auth
        - args:
            - -m
            - mlflow.server.auth
            - db
            - upgrade
            - --url
            - postgresql://bn_mlflow:$(MLFLOW_DATABASE_PASSWORD)@mlflow-postgresql:5432/bitnami_mlflow_auth
          command:
            - python
          env:
--
                secretKeyRef:
                  key: password
                  name: mlflow-postgresql
          image: docker.io/bitnami/mlflow:3.1.1-debian-12-r0
          imagePullPolicy: IfNotPresent
          name: upgrade-db-auth
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
--
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/component: provisioning
    app.kubernetes.io/instance: mlflow
    app.kubernetes.io/managed-by: Helm
```

---

Note that there is no change in this output when toggling `runUpgradeDb: true/false`; the default upgrade for the DB auth is always there, not the actual DB migration upgrade that happens when specifying it using `helm` directly. Same thing happens with another key `existingSecretAccessKeyIdKey`, because in the helm chart it's specified `existingSecretAccessKeyIDKey` (`ID` vs `Id`). So in that situation it's always looking for the default key 'root-user' and not what is specified in that field.

### Environment:

  - **Framework Version**: 2.200.109 / 2.200.111
  - **OS**:  Fedora

---

This is :bug: Bug Report
