### ISSUE TITLE
Add support for specifying selectors in Service from kplus

### ISSUE THREAD

**Issue by matheushent** [cdk8s-team/cdk8s#621]
### Description of the feature or enhancement:
I propose a feature to specify the selectors when using cdk8s-plus-17 and defining services

### Use Case:
Suppose the following code:

```python
import cdk8s_plus_17 as kplus

service = kplus.Service(
            self,
            "Service",
            type=kplus.ServiceType.NODE_PORT,
            ports=[
                kplus.ServicePort(
                    port=80, target_port=80, protocol=kplus.Protocol.TCP
                )
            ],
            metadata=cdk8s.ApiObjectMetadata(
                labels={
                    "name": "service-2048"
                }
            )
        )
```

This will generate the following manifest

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: service-2048
  name: test-service-c85b0531
spec:
  externalIPs: []
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector: {}
  type: NodePort
```

As we can see, there is no way of defining the selector specifically

### Proposed Solution:
The following code would handle:

```python
import cdk8s_plus_17 as kplus

service = kplus.Service(
            self,
            "Service",
            type=kplus.ServiceType.NODE_PORT,
            ports=[
                kplus.ServicePort(
                    port=80, target_port=80, protocol=kplus.Protocol.TCP
                )
            ],
            metadata=cdk8s.ApiObjectMetadata(
                labels={
                    "name": "service-2048"
                }
            ),
            selector={"key": "value"}
        )
```

### Other:

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request
