### ISSUE TITLE
Missing dependency breaks init python app

### ISSUE THREAD

**Issue by rt711** [cdk8s-team/cdk8s#740]
### Description of the bug:

ck8s python app can't be initialized

### Reproduction Steps:

Following github actions can run to test it, fails on init:

```
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs nodejs and npm install
      - name: Install nodejs and npm
        run: sudo apt-get -y install nodejs npm

      # Runs pipenv install
      - name: Install pipenv
        run: sudo apt-get -y install pipenv
        
      # CDK8s install  
      - name: Run cdk8s install
        run: sudo npm install -g cdk8s-cli

        # Create build dir
      - name: Run create build_test
        run: mkdir build_test

      # Run init
      - name: Initialize app
        run: cdk8s init python-app
        working-directory: ./build_test

      # Create imports
      - name: Run import
        run: cdk8s import
        working-directory: ./build_test

      # CDK8s synth
      - name: Run import
        run: cdk8s synth
        working-directory: ./build_test
```
### Error Log:

```Run cdk8s init python-app
Initializing a project from the python-app template
Creating a virtualenv for this project…
Using /usr/bin/python3 (3.8.10) to create virtualenv…
created virtual environment CPython3.8.10.final.0-64 in 350ms
  creator CPython3Posix(dest=/home/runner/.local/share/virtualenvs/build_test-aMC-R7qK, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/home/runner/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Virtualenv location: /home/runner/.local/share/virtualenvs/build_test-aMC-R7qK
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (024acd)!
Installing dependencies from Pipfile.lock (024acd)…
To activate this project's virtualenv, run the following:
 $ pipenv shell
Installing cdk8s~=1.1.19…
Collecting cdk8s~=1.1.19
  Downloading cdk8s-1.1.19-py3-none-any.whl (273 kB)
Requirement already satisfied: jsii<2.0.0,>=1.41.0 in /home/runner/.local/share/virtualenvs/build_test-aMC-R7qK/lib/python3.8/site-packages (from cdk8s~=1.1.19) (1.41.0)
Requirement already satisfied: publication>=0.0.3 in /home/runner/.local/share/virtualenvs/build_test-aMC-R7qK/lib/python3.8/site-packages (from cdk8s~=1.1.19) (0.0.3)
Requirement already satisfied: constructs<4.0.0,>=3.3.161 in /home/runner/.local/share/virtualenvs/build_test-aMC-R7qK/lib/python3.8/site-packages (from cdk8s~=1.1.19) (3.3.161)
Requirement already satisfied: python-dateutil in /home/runner/.local/share/virtualenvs/build_test-aMC-R7qK/lib/python3.8/site-packages (from jsii<2.0.0,>=1.41.0->cdk8s~=1.1.19) (2.8.2)
Requirement already satisfied: attrs~=21.2 in /home/runner/.local/share/virtualenvs/build_test-aMC-R7qK/lib/python3.8/site-packages (from jsii<2.0.0,>=1.41.0->cdk8s~=1.1.19) (21.2.0)
Requirement already satisfied: typing-extensions~=3.7 in /home/runner/.local/share/virtualenvs/build_test-aMC-R7qK/lib/python3.8/site-packages (from jsii<2.0.0,>=1.41.0->cdk8s~=1.1.19) (3.10.0.2)
Requirement already satisfied: cattrs~=1.8.0; python_version >= "3.7" in /home/runner/.local/share/virtualenvs/build_test-aMC-R7qK/lib/python3.8/site-packages (from jsii<2.0.0,>=1.41.0->cdk8s~=1.1.19) (1.8.0)
Requirement already satisfied: six>=1.5 in /home/runner/.local/share/virtualenvs/build_test-aMC-R7qK/lib/python3.8/site-packages (from python-dateutil->jsii<2.0.0,>=1.41.0->cdk8s~=1.1.19) (1.16.0)
Installing collected packages: cdk8s
Successfully installed cdk8s-1.1.19

Adding cdk8s~=1.1.19 to Pipfile's [packages]…
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipenv/project.py", line 527, in write_toml
    formatted_data = contoml.dumps(data).rstrip()
  File "/usr/lib/python3/dist-packages/pipenv/patched/contoml/__init__.py", line 36, in dumps
    raise RuntimeError("Can only dump a TOMLFile instance loaded by load() or loads()")
RuntimeError: Can only dump a TOMLFile instance loaded by load() or loads()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 349, in install
    core.do_install(
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 1979, in do_install
    project.add_package_to_pipfile(package_name, dev)
  File "/usr/lib/python3/dist-packages/pipenv/project.py", line 610, in add_package_to_pipfile
    self.write_toml(p)
  File "/usr/lib/python3/dist-packages/pipenv/project.py", line 530, in write_toml
ackage in data[section]:
KeyError: 'dev-packages'
Error: error during project initialization: Error: Command failed: pipenv install --pre cdk8s~=1.1.19
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at Object.exports.post (/usr/local/lib/node_modules/cdk8s-cli/templates/python-app/.hooks.sscaff.js:32:3)
    at executePostHook (/usr/local/lib/node_modules/cdk8s-cli/node_modules/sscaff/lib/sscaff.js:81:37)
    at sscaff (/usr/local/lib/node_modules/cdk8s-cli/node_modules/sscaff/lib/sscaff.js:48:15)
    at async Object.handler (/usr/local/lib/node_modules/cdk8s-cli/lib/cli/cmds/init.js:51:13)
STDOUT:
undefined
STDERR:
undefined
    at Object.handler (/usr/local/lib/node_modules/cdk8s-cli/lib/cli/cmds/init.js:55:19)
Error: Process completed with exit code 1.
```

### Environment:

  - **Framework Version**: 1.1.19
  - **OS**: ubuntu:latest

### Other:

Looks like the Pipfile has a missing dependency, by adding the following and re-running init the problem is fixed:

```
cdk8s = "~=1.1.19"
```

---

This is :bug: Bug Report
