### ISSUE TITLE
Invalid template metadata labels generated

### ISSUE THREAD

**Issue by markusl** [cdk8s-team/cdk8s#791]
### Description of the bug:

Consider the following cdk8s code:

```ts

import { Construct } from 'constructs';
import * as kplus from 'cdk8s-plus-22';
import { Chart, ChartProps } from 'cdk8s';

export const PodLabels = {
  'custom-label-1': 'value1',
  'custom-label-2': 'value2',
  'custom-label-3': 'value3',
};

export class TestChart extends Chart {
  constructor(scope: Construct, id: string, props: ChartProps = { }) {
    super(scope, id, props);

    const deployment1 = new kplus.Deployment(this, 'deployment1', {
      metadata: {
        name: `${id}-deployment1`,
        namespace: 'testns',
      },
      podMetadata: {
        labels: PodLabels,
      }
    });
    deployment1.addContainer({
      image: 'paulbouwer/hello-kubernetes',
      port: 8080
    });

    const deployment2 = new kplus.Deployment(this, 'deployment2', {
      metadata: {
        name: `${id}-deployment2`,
        namespace: 'testns',
      },
      podMetadata: {
        labels: PodLabels,
      }
    });
    deployment2.addContainer({
      image: 'paulbouwer/hello-kubernetes',
      port: 8080
    });
  }
}

```

The following template is generated where there's invalid label `        cdk8s.deployment: testchart-deployment2-c87e348b` under the deployment 1.

```yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testchart-deployment1
  namespace: testns
spec:
  replicas: 1
  selector:
    matchLabels:
      cdk8s.deployment: testchart-deployment1-c87d5b0d
  template:
    metadata:
      labels:
        cdk8s.deployment: testchart-deployment2-c87e348b
        custom-label-1: value1
        custom-label-2: value2
        custom-label-3: value3
    spec:
      containers:
        - env: []
          image: paulbouwer/hello-kubernetes
          imagePullPolicy: Always
          name: main
          ports:
            - containerPort: 8080
          volumeMounts: []
      volumes: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testchart-deployment2
  namespace: testns
spec:
  replicas: 1
  selector:
    matchLabels:
      cdk8s.deployment: testchart-deployment2-c87e348b
  template:
    metadata:
      labels:
        cdk8s.deployment: testchart-deployment2-c87e348b
        custom-label-1: value1
        custom-label-2: value2
        custom-label-3: value3
    spec:
      containers:
        - env: []
          image: paulbouwer/hello-kubernetes
          imagePullPolicy: Always
          name: main
          ports:
            - containerPort: 8080
          volumeMounts: []
      volumes: []

```

### Environment:

  - **Framework Version**:
    "cdk8s": "^1.2.11",
    "cdk8s-plus-22": "^1.0.0-beta.62",
  - **OS**: macOS

### Other:

---

This is :bug: Bug Report
