### ISSUE TITLE
"Reverse Engineer" existing manifests

### ISSUE THREAD

**Issue by RafaelMoreira1180778** [cdk8s-team/cdk8s#843]
### Description of the feature or enhancement:

A way to take an existing manifest and revert it into a construct of a desired language.
Something like `cdk8s ingest foo-bar.yaml`.

For instance take a simple deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: hello-world
          image: gcr.io/google-samples/node-hello:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
```

and convert it into the typescript block equivalent:

```
new KubeDeployment(new Chart(new App(), 'example-chart'), 'example-deployment', {
    metadata:
    {
        name: 'hello-world'
    },
    spec:
    {
        selector:
        {
            matchLabels:
            {
                run: 'load-balancer-example'
            }
        },
        replicas: 2,
        template:
        {
            metadata:
            {
                labels:
                {
                    run: 'load-balancer-example'
                }
            },
            spec:
            {
                containers:
                    [
                        {
                            name: 'hello-world',
                            image: 'gcr.io/google-samples/node-hello:1.0',
                            ports:
                                [
                                    {
                                        containerPort: 8080,
                                        protocol: IoK8SApiCoreV1ContainerPortProtocol.TCP
                                    }
                                ]
                        }
                    ]
            }
        }
    }
})
```

### Use Case:

I find myself converting old manifests to cdk8s constructs and projects and some of them can be very long and they are standerdized (as in: no CRDs) so ingesting them into my projects would be nice.

### Other:

Using parameters an app/chart could be created for the converted manifests to be associate with.

---

This is a :rocket: Feature Request
