### ISSUE TITLE
Allow importing multiple CRDs in the same namespace

### ISSUE THREAD

**Issue by mcouthon** [cdk8s-team/cdk8s#885]
### Description of the feature or enhancement:

Allow multiple CRDs with the same spec group to be imported using `cdk8s import`.

### Use Case:

I have this `cdk8s.yaml`:

```yaml
language: python
imports:
    - k8s
    - https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.3.1/config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.3.1/config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
```

Using it as is with `cdk8s import` results in the second CRD overwriting the first one in my `imports` folder.

Meaning, it results in the file `imports/aws/k8s/elbv2/__init__.py` having this at the bottom (resources only from the second CRD YAML):

```python
__all__ = [
    "TargetGroupBinding",
    "TargetGroupBindingProps",
    "TargetGroupBindingSpec",
    "TargetGroupBindingSpecNetworking",
    "TargetGroupBindingSpecNetworkingIngress",
    "TargetGroupBindingSpecNetworkingIngressFrom",
    "TargetGroupBindingSpecNetworkingIngressFromIpBlock",
    "TargetGroupBindingSpecNetworkingIngressFromSecurityGroup",
    "TargetGroupBindingSpecNetworkingIngressPorts",
    "TargetGroupBindingSpecNetworkingIngressPortsPort",
    "TargetGroupBindingSpecNetworkingIngressPortsProtocol",
    "TargetGroupBindingSpecServiceRef",
    "TargetGroupBindingSpecServiceRefPort",
    "TargetGroupBindingSpecTargetType",
]
```

Obviously, switching the two YAMLs places will result in the opposite effect.

### Proposed Solution:

A current workaround is to use aliases, like this:

```yaml
language: python
imports:
    - k8s
    - ingressclassparams:=https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.3.1/config/crd/bases/elbv2.k8s.aws_ingressclassparams.yaml
    - targetgroupbindings:=https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.3.1/config/crd/bases/elbv2.k8s.aws_targetgroupbindings.yaml
```

This is ok, but it's inconvenient. A better outcome would be to combine the two. Meaning, `imports/aws/k8s/elbv2/__init__.py` will have both of the YAMLs' resources in it:

```python
__all__ = [
    "IngressClassParams",
    "IngressClassParamsProps",
    "IngressClassParamsSpec",
    "IngressClassParamsSpecGroup",
    "IngressClassParamsSpecIpAddressType",
    "IngressClassParamsSpecLoadBalancerAttributes",
    "IngressClassParamsSpecNamespaceSelector",
    "IngressClassParamsSpecNamespaceSelectorMatchExpressions",
    "IngressClassParamsSpecScheme",
    "IngressClassParamsSpecTags",
    "TargetGroupBinding",
    "TargetGroupBindingProps",
    "TargetGroupBindingSpec",
    "TargetGroupBindingSpecNetworking",
    "TargetGroupBindingSpecNetworkingIngress",
    "TargetGroupBindingSpecNetworkingIngressFrom",
    "TargetGroupBindingSpecNetworkingIngressFromIpBlock",
    "TargetGroupBindingSpecNetworkingIngressFromSecurityGroup",
    "TargetGroupBindingSpecNetworkingIngressPorts",
    "TargetGroupBindingSpecNetworkingIngressPortsPort",
    "TargetGroupBindingSpecNetworkingIngressPortsProtocol",
    "TargetGroupBindingSpecServiceRef",
    "TargetGroupBindingSpecServiceRefPort",
    "TargetGroupBindingSpecTargetType",
]
```

### Other:

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by jeverett1522** [comment]
This is a big issue that is hitting us right now also.  Any progress would be much appreciated!

**Comment by Nageshbansal** [comment]
@iliapolo, can I work on this issue?

**Comment by shinebayar-g** [comment]
I was confused a little bit until I find this post. I'm glad that aliasing exists. I found out I could merge all of the CRDs into a giant yaml file, but this gives back a giant single file. If CRDs are generated in more organized structure and exported from a single entrtypoint file that'd be a super helpful.

**Comment by yuriy-yarosh** [comment]
Well, faced the same with Crossplane

```yaml
app: go mod download && go mod tidy && go run .
language: go
imports:
  - https://raw.githubusercontent.com/crossplane/crossplane/master/cluster/crds/apiextensions.crossplane.io_environmentconfigs.yaml
  - https://raw.githubusercontent.com/crossplane/crossplane/master/cluster/crds/apiextensions.crossplane.io_compositions.yaml
```

Which overwrites envconfigs with compositions :\

**Comment by bderrly** [comment]
I have written a Bash script to handle this while a better solution is forthcoming. The script pulls down the CRDs from the cluster and merges any with the same kind into a single YAML file. I then import the single file normally: `cdk8s import crds/*.yaml`.

```bash
#!/usr/bin/env bash

PROJECT_ROOT=$(pwd)
CRD_PATH="${PROJECT_ROOT}/crds"

CRDS=(
    vaultauths.secrets.hashicorp.com
    vaultstaticsecrets.secrets.hashicorp.com
    )

if [[ ! -d "${CRD_PATH}" ]]; then
    mkdir "${CRD_PATH}"
fi

for crd in "${CRDS[@]}"; do
    group=${crd#[a-z]*.} # strip kind
    echo "---" >> "${CRD_PATH}/${group}.yaml"
    kubectl get "crd/${crd}" -o yaml >> "${CRD_PATH}/${group}.yaml"
    echo "fetched ${crd}"
done
```

**Comment by LS80** [comment]
I do it like this
```shell
yq \
    <(wget -qO - https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.0/manifests/crds/application-crd.yaml) \
    <(wget -qO - https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.0/manifests/crds/applicationset-crd.yaml) \
    | cdk8s import --language python /dev/stdin
```
Hopefully this will get fixed at some point as we won't need the workarounds.

**Comment by benkeil** [comment]
Is there a solution? How can you use this tool without that feature?

I think a better solution is how Terraform CDK handles it:

```json
"terraformModules": [
  {
    "name": "security-group",
    "source": "terraform-aws-modules/security-group/aws",
    "version": "~> 5.1"
  }
],
```

Like this you are open to add other features to an import. Maybe leave import like it is and a a second field, maybe not...

```yaml
imports:
  - k8s
crds:
  - name: issuers
    source: https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/crd-issuers
  - name: clusterissuers
    source: https://raw.githubusercontent.com/cert-manager/cert-manager/master/deploy/crds/crd-clusterissuers.yaml
```

**Comment by gpolumbo-foreflight** [comment]
This problem also exists in Java.  The confusing part was that the class files for both CRDs existed in the source code, so when I was getting errors that the class could not be found, I was chasing my tail for a while because I could literally see that the class was there.  The issue was that in the `resources/[module_name]/$Module.txt` file, it only has the definitions for one of the CRDs.

**Comment by renannprado** [comment]
Building on @LS80's idea, I keep the CRDs committed and referenced in the `cdk8s.yaml`

```yaml
language: java
app: mvn exec:java -Dexec.mainClass="com.mycompany.app.Main"
imports:
  - src/crds/ingressroutes.traefik.io.yaml
  - src/crds/middlewares.traefik.io.yaml
```

And then:

```shell
yq '.imports | join(" ")' cdk8s.yaml | xargs yq | cdk8s import /dev/stdin
```

Concatenating multiple CRDs into a single file and referencing it in the `imports` property also works.
