### ISSUE TITLE
Add Deployment Strategy in plus-22

### ISSUE THREAD

**Issue by rohitranjan1991** [cdk8s-team/cdk8s#891]
How can I add Deployment strategy equivalent to the below in plus-22:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc
  namespace: "default"
  labels:
    app: abc
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc
  strategy: //////////////////////////////////// this one
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
```
