### ISSUE TITLE
Using JsonPatch to add a volumeClaimTemplate with a storage request results in null storage request in yaml

### ISSUE THREAD

**Issue by jpmartin2** [cdk8s-team/cdk8s#908]
### Description of the bug:

I've added attempted to add volumeClaimTemplates to a StatefulSet using a JsonPatch. However while this synths fine, the resulting yaml has `storage: null` in the storage request for the volumeClaimTemplate.

### Reproduction Steps:

```
      const statefulSet = new StatefulSet(this, 'stateful-set', {
        service: headlessService,
        containers: [{
          image: 'docker.io/gitlab/gitlab-ce',
          volumeMounts: [
            // ...
          ],
        }]
      });
      ApiObject.of(statefulSet).addJsonPatch(
        JsonPatch.replace('/spec/volumeClaimTemplates', [{
            metadata: {
              name: 'gitlab-persistence',
            },
            spec: {
              accessModes: ['ReadWriteOnce'],
              storageClassName: props.storageClass.name,
              resources: {
                requests: {
                  storage: '50Gi',
                }
              },
            },
        }]),
        JsonPatch.add('/spec/template/spec/containers/0/volumeMounts/0', {
            name: 'gitlab-persistence',
            mountPath: '/var/opt/gitlab',
            subPath: 'data',
        }),
        JsonPatch.add('/spec/template/spec/containers/0/volumeMounts/0', {
            name: 'gitlab-persistence',
            mountPath: '/var/log/gitlab',
            subPath: 'logs',
        }),
      );
```

However, the resulting yaml does not have `storage: 50Gi` as expected, instead it has `storage: null`:

```
  volumeClaimTemplates:
    - metadata:
        name: gitlab-persistence
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: null
        storageClassName: ceph-block
```

### Environment:

  - **Framework Version**: cdk8s 1.5.76, cdk8s-cli 1.0.155, cdk8s-plus-22 1.0.0-beta.200, 
  - **OS**: Fedora 36 Beta

---

This is :bug: Bug Report
