### ISSUE TITLE
Helm Chart - List Resource not propagating namespace to items

### ISSUE THREAD

**Issue by Jaskerv** [cdk8s-team/cdk8s#948]
### Description of the bug:

I am using a Traefik Helm Chart with namespace. When performing synth, the item is missing the namespace,

**Output**
```
apiVersion: v1
kind: List
metadata:
  name: traefik-helm-c804c43d
  namespace: hello-world-c8d24ded
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/instance: traefik-helm-c804c43d
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-10.24.0
      name: traefik-helm-c804c43d
    spec:
      ports:
        - name: web
          port: 80
          protocol: TCP
          targetPort: web
        - name: websecure
          port: 443
          protocol: TCP
          targetPort: websecure
      selector:
        app.kubernetes.io/instance: traefik-helm-c804c43d
        app.kubernetes.io/name: traefik
      type: LoadBalancer

```
**Expected**
```
apiVersion: v1
kind: List
metadata:
  name: traefik-helm-c804c43d
  namespace: hello-world-c8d24ded
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/instance: traefik-helm-c804c43d
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-10.24.0
      name: traefik-helm-c804c43d
      namespace: hello-world-c8d24ded
    spec:
      ports:
        - name: web
          port: 80
          protocol: TCP
          targetPort: web
        - name: websecure
          port: 443
          protocol: TCP
          targetPort: websecure
      selector:
        app.kubernetes.io/instance: traefik-helm-c804c43d
        app.kubernetes.io/name: traefik
      type: LoadBalancer

```

### Reproduction Steps:

1. Create this class:
```
export default class Traefik extends Chart {
  constructor(scope: Construct, id: string, props: ChartProps) {
    super(scope, id, props);

    let helmFlags: string[] = [];
    if (props.namespace) {
      helmFlags = ['--namespace', props.namespace];
    }

    new Helm(this, 'helm', {
      chart: 'traefik/traefik',
      helmFlags: helmFlags,
    });
  }
}
```
2. Pass in a namespace
3. Synth

### Environment:

  - **Framework Version**:
  - **OS**:

### Other:

---

This is :bug: Bug Report
