### ISSUE TITLE
Can't add securityContext -> Capabilities -> NET_ADMIN ?

### ISSUE THREAD

**Issue by NinoSkopac** [cdk8s-team/cdk8s#981]
In YAML, I'd do this:

```yaml
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
```

But I can't figure out how to do that, apart from using Escape Hatches, which I also don't understand given current examples on the docs page.

I tried as a Pod and as a Deployment.
I'm aware `PodSecurityContextProps` but that has different options.
